### ISSUE TITLE
Environment Instruction

### ISSUE THREAD

**Issue by casivido** [inopinatus/sublime_url#1]
Hi, this repo is awesome. I would love to throw up an MR/PR allowing one url to open multiple files in Sublime, but I was having trouble correctly compiling the source code. If willing, could you throw up some environment setup instructions?

* I opened the source code in script editor and exported as application, but all results failed to correctly set up the scheme after moving to applications and running. (First venture into AppleScript, but I assume it would be for many who would like to contribute.)

**Comment by inopinatus** [comment]
Hi, and thanks for the kind remark.

I just edit the .scpt files in `SublimeUrl.app/Contents/Resources/Scripts` directly using Script Editor. The contents of src/ is there for documentation purposes and casual repo browsers, since the .scpt files are binary.

You'll probably need to delete any existing installed /Applications/SublimeUrl.app and/or ~/Applications/SublimeUrl.app to be sure they're not being invoked instead. Or use [RCDefaultApp](http://www.rubicode.com/Software/RCDefaultApp/) to check the currently installed URL handler.

NB: I'm not sure I'd accept a PR for opening multiple files without understanding and accepting the use case. This microscopic and simple app is intended as a bridge between `better_errors` and Sublime Text 3, for which case only one file is ever passed.
